<?php

namespace Database\Seeders;

use App\Models\Produto;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class ProdutoSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        Produto::Create(['id'=>8, 	'status_id'=> 1 ,'categoria_id' =>1,  'unidade' => 'UNID', 'nome'=> 'Panela 5', 						'eh_produto'=> 'S', 'eh_insumo' => 'N', 'preco_venda'=>'100.00', 'preco_custo'=>'50.00', 		'imagem'=> 'upload/produtos/PANELA_5.jpg', 						'gtin'=> 'SEM GTIN', 'ncm'=> '85167910', 'estoque_minimo'=> 10]);
        Produto::Create(['id'=>9, 	'status_id'=> 1 ,'categoria_id' =>1,  'unidade' => 'UNID', 'nome'=> 'Panela de Pressão', 			'eh_produto'=> 'S', 'eh_insumo' => 'N', 'preco_venda'=>'100.00', 'preco_custo'=>'50.00', 		'imagem'=> 'upload/produtos/PANELA_DE_PRESAO.png', 				'gtin'=> 'SEM GTIN', 'ncm'=> '85167910', 'estoque_minimo'=> 10]);
        Produto::Create(['id'=>10, 	'status_id'=> 1 ,'categoria_id' =>7,  'unidade' => 'UNID', 'nome'=> 'Frigideira Reforçada', 			'eh_produto'=> 'S', 'eh_insumo' => 'N', 'preco_venda'=>'497.00', 'preco_custo'=>'397.00', 		'imagem'=> 'upload/produtos/FRIGIDEIRA_REFORCADA.jpg', 			'gtin'=> 'SEM GTIN', 'ncm'=> '85167910', 'estoque_minimo'=> 10]);
        Produto::Create(['id'=>11, 	'status_id'=> 1 ,'categoria_id' =>7,  'unidade' => 'UNID', 'nome'=> 'Frigideira Cabo Tubular', 		'eh_produto'=> 'S', 'eh_insumo' => 'N', 'preco_venda'=>'100.00', 'preco_custo'=>'50.00', 		'imagem'=> 'upload/produtos/FRIGIDEIRA_CABO_TUBULAR_2.jpg', 	'gtin'=> 'SEM GTIN', 'ncm'=> '85167910', 'estoque_minimo'=> 10]);
        Produto::Create(['id'=>12, 	'status_id'=> 1 ,'categoria_id' =>1,  'unidade' => 'UNID', 'nome'=> 'Panela Longa', 					'eh_produto'=> 'S', 'eh_insumo' => 'N', 'preco_venda'=>'100.00', 'preco_custo'=>'50.00', 		'imagem'=> 'upload/produtos/PANELA_LONGA.jpg', 					'gtin'=> 'SEM GTIN', 'ncm'=> '85167910', 'estoque_minimo'=> 10]);
        Produto::Create(['id'=>13, 	'status_id'=> 1 ,'categoria_id' =>1,  'unidade' => 'UNID', 'nome'=> 'Panela Arredondada', 			'eh_produto'=> 'S', 'eh_insumo' => 'N', 'preco_venda'=>'100.00', 'preco_custo'=>'50.00', 		'imagem'=> 'upload/produtos/PANELA_RREDONDADA2.jpg', 			'gtin'=> 'SEM GTIN', 'ncm'=> '85167910', 'estoque_minimo'=> 10]);
        Produto::Create(['id'=>14, 	'status_id'=> 1 ,'categoria_id' =>1,  'unidade' => 'UNID', 'nome'=> 'Panela Laranja', 				'eh_produto'=> 'S', 'eh_insumo' => 'N', 'preco_venda'=>'50.00',  'preco_custo'=>'30.00',  		'imagem'=> 'upload/produtos/PANELA_LARANJA.jpg', 				'gtin'=> 'SEM GTIN', 'ncm'=> '85167910', 'estoque_minimo'=> 10]);
        Produto::Create(['id'=>15, 	'status_id'=> 1 ,'categoria_id' =>1,  'unidade' => 'UNID', 'nome'=> 'Panela Longa 2', 				'eh_produto'=> 'S', 'eh_insumo' => 'N', 'preco_venda'=>'100.00', 'preco_custo'=>'50.00', 		'imagem'=> 'upload/produtos/PANELA_LONGA2.jpg', 				'gtin'=> 'SEM GTIN', 'ncm'=> '85167910', 'estoque_minimo'=> 10]);
        Produto::Create(['id'=>16, 	'status_id'=> 1 ,'categoria_id' =>1,  'unidade' => 'UNID', 'nome'=> 'Panela Achatada', 				'eh_produto'=> 'S', 'eh_insumo' => 'N', 'preco_venda'=>'100.00', 'preco_custo'=>'50.00', 		'imagem'=> 'upload/produtos/PANELA_ACHATADA.jpg', 				'gtin'=> 'SEM GTIN', 'ncm'=> '85167910', 'estoque_minimo'=> 10]);
        Produto::Create(['id'=>17, 	'status_id'=> 1 ,'categoria_id' =>1,  'unidade' => 'UNID', 'nome'=> 'Panela Achatada 2', 			'eh_produto'=> 'S', 'eh_insumo' => 'N', 'preco_venda'=>'100.00', 'preco_custo'=>'50.00', 		'imagem'=> 'upload/produtos/PANELA_ACHATADA2.jpg', 				'gtin'=> 'SEM GTIN', 'ncm'=> '85167910', 'estoque_minimo'=> 10]);
        Produto::Create(['id'=>18, 	'status_id'=> 1 ,'categoria_id' =>1,  'unidade' => 'UNID', 'nome'=> 'Panela Verde', 					'eh_produto'=> 'S', 'eh_insumo' => 'N', 'preco_venda'=>'100.00', 'preco_custo'=>'100.00', 		'imagem'=> 'upload/produtos/PANELA_VERDE.jpg', 					'gtin'=> 'SEM GTIN', 'ncm'=> '85167910', 'estoque_minimo'=> 10]);
        Produto::Create(['id'=>19, 	'status_id'=> 1 ,'categoria_id' =>1,  'unidade' => 'UNID', 'nome'=> 'Panela Verde 2', 				'eh_produto'=> 'S', 'eh_insumo' => 'N', 'preco_venda'=>'100.00', 'preco_custo'=>'100.00', 		'imagem'=> 'upload/produtos/PANELA_VERDE2.jpg', 				'gtin'=> 'SEM GTIN', 'ncm'=> '85167910', 'estoque_minimo'=> 10]);
        Produto::Create(['id'=>20, 	'status_id'=> 1 ,'categoria_id' =>7,  'unidade' => 'UNID', 'nome'=> 'Frigideira sem Tampa Laranja', 	'eh_produto'=> 'S', 'eh_insumo' => 'N', 'preco_venda'=>'100.00', 'preco_custo'=>'100.00', 		'imagem'=> 'upload/produtos/FRIGIDEIRA_SEM_TAMPA_LARANJA.jpg',  'gtin'=> 'SEM GTIN', 'ncm'=> '85167910', 'estoque_minimo'=> 10]);
        Produto::Create(['id'=>21, 	'status_id'=> 1 ,'categoria_id' =>7,  'unidade' => 'UNID', 'nome'=> 'Frigideira Laranja', 			'eh_produto'=> 'S', 'eh_insumo' => 'N', 'preco_venda'=>'100.00', 'preco_custo'=>'100.00', 		'imagem'=> 'upload/produtos/FRIGIDEIRA_LARANJA.jpg', 			'gtin'=> 'SEM GTIN', 'ncm'=> '85167910', 'estoque_minimo'=> 10]);
        Produto::Create(['id'=>22, 	'status_id'=> 1 ,'categoria_id' =>2,  'unidade' => 'UNID', 'nome'=> 'Cuscuzeira Laranja', 			'eh_produto'=> 'S', 'eh_insumo' => 'N', 'preco_venda'=>'100.00', 'preco_custo'=>'100.00', 		'imagem'=> 'upload/produtos/CUSCUZEIRA_LARANJA.jpg', 			'gtin'=> 'SEM GTIN', 'ncm'=> '85167910', 'estoque_minimo'=> 10]);
        Produto::Create(['id'=>31, 	'status_id'=> 1 ,'categoria_id' =>2,  'unidade' => 'UNID', 'nome'=> 'Cuscuzeira 3', 					'eh_produto'=> 'S', 'eh_insumo' => 'N', 'preco_venda'=>'150.00', 'preco_custo'=>'150.00', 		'imagem'=> 'upload/produtos/CUSCUZEIRA3.jpg', 					'gtin'=> 'SEM GTIN', 'ncm'=> '85167910', 'estoque_minimo'=> 10]);
        Produto::Create(['id'=>32, 	'status_id'=> 1 ,'categoria_id' =>6,  'unidade' => 'UNID', 'nome'=> 'Leiteira Tubular 3', 			'eh_produto'=> 'S', 'eh_insumo' => 'N', 'preco_venda'=>'50.00',  'preco_custo'=>'50.00',  		'imagem'=> 'upload/produtos/LEITEIRAS_TUBULAR3.jpg', 			'gtin'=> 'SEM GTIN', 'ncm'=> '85167910', 'estoque_minimo'=> 10]);
        Produto::Create(['id'=>33, 	'status_id'=> 1 ,'categoria_id' =>6,  'unidade' => 'UNID', 'nome'=> 'Leiteira com Tampa Laranja', 	'eh_produto'=> 'S', 'eh_insumo' => 'N', 'preco_venda'=>'30.00',  'preco_custo'=>'30.00',  		'imagem'=> 'upload/produtos/LEITEIRA_COM_TAMPA_LARANJA4.jpg', 	'gtin'=> 'SEM GTIN', 'ncm'=> '85167910', 'estoque_minimo'=> 10]);
        Produto::Create(['id'=>35, 	'status_id'=> 1 ,'categoria_id' =>1,  'unidade' => 'UNID', 'nome'=> 'Panela com tampa 2', 			'eh_produto'=> 'S', 'eh_insumo' => 'N', 'preco_venda'=>'100.00', 'preco_custo'=>'100.00', 		'imagem'=> 'upload/produtos/PANELA_COM_TAMPA_2.jpg', 			'gtin'=> 'SEM GTIN', 'ncm'=> '85167910', 'estoque_minimo'=> 10]);
        Produto::Create(['id'=>38, 	'status_id'=> 1 ,'categoria_id' =>11, 'unidade' => 'UNID', 'nome'=> 'ABRASIVO CEBO AMARELO', 		'eh_produto'=> 'N', 'eh_insumo' => 'S', 'preco_venda'=>'15.70',  'preco_custo'=>'15.70',  		'imagem'=> Null, 												'gtin'=> 'SEM GTIN', 'ncm'=> '85167910', 'estoque_minimo'=> 10]);
        Produto::Create(['id'=>41, 	'status_id'=> 1 ,'categoria_id' =>11, 'unidade' => 'UNID', 'nome'=> 'ALCA PARA TAMPA', 				'eh_produto'=> 'N', 'eh_insumo' => 'S', 'preco_venda'=>'15.90',  'preco_custo'=>'15.90',  		'imagem'=> null, 												'gtin'=> 'SEM GTIN', 'ncm'=> '85167910', 'estoque_minimo'=> 10]);
        Produto::Create(['id'=>52, 	'status_id'=> 1 ,'categoria_id' =>11, 'unidade' => 'UNID', 'nome'=> 'ALÇA DE LEITEIRA', 				'eh_produto'=> 'N', 'eh_insumo' => 'S', 'preco_venda'=>'0.50', 	 'preco_custo'=>'0.50', 		'imagem'=> null, 												'gtin'=> 'SEM GTIN', 'ncm'=> '85167910', 'estoque_minimo'=> 10]);
        Produto::Create(['id'=>57, 	'status_id'=> 1 ,'categoria_id' =>11, 'unidade' => 'UNID', 'nome'=> 'ALÇA PARA PANELA DE PRESSAO', 	'eh_produto'=> 'N', 'eh_insumo' => 'S', 'preco_venda'=>'0.40', 	 'preco_custo'=>'0.40', 		'imagem'=> null, 												'gtin'=> 'SEM GTIN', 'ncm'=> '85167910', 'estoque_minimo'=> 10]);
        Produto::Create(['id'=>60, 	'status_id'=> 1 ,'categoria_id' =>11, 'unidade' => 'UNID', 'nome'=> 'BORRACHAS P/ PANELA PRESSAO', 	'eh_produto'=> 'N', 'eh_insumo' => 'S', 'preco_venda'=>'0.50', 	 'preco_custo'=>'0.50', 		'imagem'=> null, 												'gtin'=> 'SEM GTIN', 'ncm'=> '85167910', 'estoque_minimo'=> 10]);
        Produto::Create(['id'=>61, 	'status_id'=> 1 ,'categoria_id' =>11, 'unidade' => 'UNID', 'nome'=> 'CABO CUSCUZEIRA ', 				'eh_produto'=> 'N', 'eh_insumo' => 'S', 'preco_venda'=>'0.65', 	 'preco_custo'=>'0.65', 		'imagem'=> null, 												'gtin'=> 'SEM GTIN', 'ncm'=> '85167910', 'estoque_minimo'=> 10]);
        Produto::Create(['id'=>62, 	'status_id'=> 1 ,'categoria_id' =>11, 'unidade' => 'UNID', 'nome'=> 'CABO DE CAÇAROLA COD.227', 		'eh_produto'=> 'N', 'eh_insumo' => 'S', 'preco_venda'=>'0.90', 	 'preco_custo'=>'0.90', 		'imagem'=> null, 												'gtin'=> 'SEM GTIN', 'ncm'=> '85167910', 'estoque_minimo'=> 10]);
        Produto::Create(['id'=>63, 	'status_id'=> 1 ,'categoria_id' =>11, 'unidade' => 'UNID', 'nome'=> 'CABO DE FRIGIDEIRA PEQUENA', 	'eh_produto'=> 'N', 'eh_insumo' => 'S', 'preco_venda'=>'5.90', 	 'preco_custo'=>'5.90', 		'imagem'=> null, 												'gtin'=> 'SEM GTIN', 'ncm'=> '85167910', 'estoque_minimo'=> 10]);
        Produto::Create(['id'=>64, 	'status_id'=> 1 ,'categoria_id' =>11, 'unidade' => 'UNID', 'nome'=> 'CABO DE LEITEIRA COD.2046', 	'eh_produto'=> 'N', 'eh_insumo' => 'S', 'preco_venda'=>'1.30', 	 'preco_custo'=>'1.30', 		'imagem'=> null, 												'gtin'=> 'SEM GTIN', 'ncm'=> '85167910', 'estoque_minimo'=> 10]);
        Produto::Create(['id'=>85, 	'status_id'=> 1 ,'categoria_id' =>11, 'unidade' => 'UNID', 'nome'=> 'CABO PARA PANELA DE PRESSAO', 	'eh_produto'=> 'N', 'eh_insumo' => 'S', 'preco_venda'=>'1.20', 	 'preco_custo'=>'1.20', 		'imagem'=> null, 												'gtin'=> 'SEM GTIN', 'ncm'=> '85167910', 'estoque_minimo'=> 10]);
        Produto::Create(['id'=>86, 	'status_id'=> 1 ,'categoria_id' =>11, 'unidade' => 'UNID', 'nome'=> 'CABO REBITADO PEQUENO 3F 90G', 	'eh_produto'=> 'N', 'eh_insumo' => 'S', 'preco_venda'=>'0.95', 	 'preco_custo'=>'0.95', 		'imagem'=> null, 												'gtin'=> 'SEM GTIN', 'ncm'=> '85167910', 'estoque_minimo'=> 10]);
        Produto::Create(['id'=>87, 	'status_id'=> 1 ,'categoria_id' =>11, 'unidade' => 'UNID', 'nome'=> 'HASTE GRANDE  20 X 130', 		'eh_produto'=> 'N', 'eh_insumo' => 'S', 'preco_venda'=>'15.90',  'preco_custo'=>'15.90', 		'imagem'=> null, 												'gtin'=> 'SEM GTIN', 'ncm'=> '85167910', 'estoque_minimo'=> 10]);
        Produto::Create(['id'=>91, 	'status_id'=> 1 ,'categoria_id' =>11, 'unidade' => 'UNID', 'nome'=> 'LIXA', 							'eh_produto'=> 'N', 'eh_insumo' => 'S', 'preco_venda'=>'0.50', 	 'preco_custo'=>'0.50', 		'imagem'=> null, 												'gtin'=> 'SEM GTIN', 'ncm'=> '85167910', 'estoque_minimo'=> 10]);
        Produto::Create(['id'=>92, 	'status_id'=> 1 ,'categoria_id' =>11, 'unidade' => 'UNID', 'nome'=> 'ORELHA DE CALDEIRAO', 			'eh_produto'=> 'N', 'eh_insumo' => 'S', 'preco_venda'=>'31.80',  'preco_custo'=>'31.80', 		'imagem'=> null, 												'gtin'=> 'SEM GTIN', 'ncm'=> '85167910', 'estoque_minimo'=> 10]);
        Produto::Create(['id'=>93, 	'status_id'=> 1 ,'categoria_id' =>11, 'unidade' => 'UNID', 'nome'=> 'PESO TIPO UNIV.PRETO S/MARCA ',  'eh_produto'=> 'N', 'eh_insumo' => 'S', 'preco_venda'=>'1.30', 	 'preco_custo'=>'1.30', 		'imagem'=> null, 												'gtin'=> 'SEM GTIN', 'ncm'=> '85167910', 'estoque_minimo'=> 10]);
        Produto::Create(['id'=>94, 	'status_id'=> 1 ,'categoria_id' =>11, 'unidade' => 'UNID', 'nome'=> 'PINO 1/2  DIAM 01 R 3/8 UNF', 	'eh_produto'=> 'N', 'eh_insumo' => 'S', 'preco_venda'=>'1.30', 	 'preco_custo'=>'1.30', 		'imagem'=> null, 												'gtin'=> 'SEM GTIN', 'ncm'=> '85167910', 'estoque_minimo'=> 10]);
        Produto::Create(['id'=>95, 	'status_id'=> 1 ,'categoria_id' =>11, 'unidade' => 'UNID', 'nome'=> 'POMEL COLOR', 					'eh_produto'=> 'N', 'eh_insumo' => 'S', 'preco_venda'=>'0.60', 	 'preco_custo'=>'0.60', 		'imagem'=> null, 												'gtin'=> 'SEM GTIN', 'ncm'=> '85167910', 'estoque_minimo'=> 10]);
        Produto::Create(['id'=>103, 'status_id'=> 1 ,'categoria_id' =>11, 'unidade' => 'UNID', 'nome'=> 'RALO 110', 						'eh_produto'=> 'N', 'eh_insumo' => 'S', 'preco_venda'=>'13.70',  'preco_custo'=>'13.70', 		'imagem'=> null, 												'gtin'=> 'SEM GTIN', 'ncm'=> '85167910', 'estoque_minimo'=> 10]);
        Produto::Create(['id'=>107, 'status_id'=> 1 ,'categoria_id' =>11, 'unidade' => 'UNID', 'nome'=> 'RIBITE 1/8  X 7   PEQUENO', 	    'eh_produto'=> 'N', 'eh_insumo' => 'S', 'preco_venda'=>'31.80',  'preco_custo'=>'31.80', 		'imagem'=> null, 												'gtin'=> 'SEM GTIN', 'ncm'=> '85167910', 'estoque_minimo'=> 10]);
        Produto::Create(['id'=>113, 'status_id'=> 1 ,'categoria_id' =>11, 'unidade' => 'UNID', 'nome'=> 'RODA DE BRIM', 					'eh_produto'=> 'N', 'eh_insumo' => 'S', 'preco_venda'=>'0.30', 	 'preco_custo'=>'0.30', 		'imagem'=> null, 												'gtin'=> 'SEM GTIN', 'ncm'=> '85167910', 'estoque_minimo'=> 10]);
        Produto::Create(['id'=>114, 'status_id'=> 1 ,'categoria_id' =>11, 'unidade' => 'UNID', 'nome'=> 'SELO DE SEGURANÇA', 			    'eh_produto'=> 'N', 'eh_insumo' => 'S', 'preco_venda'=>'0.00', 	 'preco_custo'=>'0.00', 		'imagem'=> null, 												'gtin'=> 'SEM GTIN', 'ncm'=> '85167910', 'estoque_minimo'=> 10]);
        Produto::Create(['id'=>115, 'status_id'=> 1 ,'categoria_id' =>11, 'unidade' => 'UNID', 'nome'=> 'SUPORTE ALUM. BALDE Nº02', 		'eh_produto'=> 'N', 'eh_insumo' => 'S', 'preco_venda'=>'31.80',  'preco_custo'=>'31.80', 		'imagem'=> null, 												'gtin'=> 'SEM GTIN', 'ncm'=> '85167910', 'estoque_minimo'=> 10]);
        Produto::Create(['id'=>117, 'status_id'=> 1 ,'categoria_id' =>11, 'unidade' => 'UNID', 'nome'=> 'DISC0 210 X 1,10', 				'eh_produto'=> 'N', 'eh_insumo' => 'S', 'preco_venda'=>'12.70',  'preco_custo'=>'12.70', 		'imagem'=> null, 												'gtin'=> 'SEM GTIN', 'ncm'=> '85167910', 'estoque_minimo'=> 10]);
        Produto::Create(['id'=>142, 'status_id'=> 1 ,'categoria_id' =>11, 'unidade' => 'UNID', 'nome'=> 'TAMPA LUXO 14', 				    'eh_produto'=> 'N', 'eh_insumo' => 'S', 'preco_venda'=>'1.00', 	 'preco_custo'=>'1.00', 		'imagem'=> null, 												'gtin'=> 'SEM GTIN', 'ncm'=> '85167910', 'estoque_minimo'=> 10]);
        Produto::Create(['id'=>143, 'status_id'=> 1 ,'categoria_id' =>11, 'unidade' => 'UNID', 'nome'=> 'DISC0 PARA TAMPA', 				'eh_produto'=> 'N', 'eh_insumo' => 'S', 'preco_venda'=>'1.00', 	 'preco_custo'=>'1.00', 		'imagem'=> null, 												'gtin'=> 'SEM GTIN', 'ncm'=> '85167910', 'estoque_minimo'=> 10]);
        Produto::Create(['id'=>144, 'status_id'=> 1 ,'categoria_id' =>11, 'unidade' => 'UNID', 'nome'=> 'TAMPA PARA PANELA DE PRESSÃO', 	'eh_produto'=> 'N', 'eh_insumo' => 'S', 'preco_venda'=>'1.00', 	 'preco_custo'=>'1.00', 		'imagem'=> null, 												'gtin'=> 'SEM GTIN', 'ncm'=> '85167910', 'estoque_minimo'=> 10]);
        Produto::Create(['id'=>145, 'status_id'=> 1 ,'categoria_id' =>11, 'unidade' => 'UNID', 'nome'=> 'VÁLVULA SEGURANÇA PAN. PRESSÃO', 'eh_produto'=> 'N', 'eh_insumo' => 'S', 'preco_venda'=>'1.00', 	 'preco_custo'=>'1.00', 		'imagem'=> null, 												'gtin'=> 'SEM GTIN', 'ncm'=> '85167910', 'estoque_minimo'=> 10]);
    }

}
